### PR TITLE
Posibility to generate iban with correct checksum

### PR DESCRIPTION
**Pull request by g-pavlik**
It is needed if you need to generate IBAN numbers for bank mass payments system. I'm not quite sure about name of the method, so I'm open for suggestions :)

### CODE REVIEW

**Comment by LTe** [comment]
What do you think about `recalculate_checksum`?

**Comment by g-pavlik** [comment]
Sounds good. I automatically regenerated Gemspec (to use from my fork), but it ended up in the pull request. I hope it's not a problem?

**Comment by LTe** [comment]
@pawlik [merged](https://github.com/LTe/iban-check/commit/f7c6620498c497537aed7b7316414cb3bf5cec10). Next time try to use custom branch for pull request :)

**Comment by g-pavlik** [comment]
Ok, I'll do that. Thanks

**Comment by LTe** [comment]
@pawlik and thanks for pull request :) You are awesome :)

**Comment by g-pavlik** [comment]
Pleasure :) Do you think adding polish NRB accounts features to this project makes sense?

**Comment by LTe** [comment]
To create IBAN number from NRB developer need only add country code before number. You can also execute iban with country param

``` ruby
IbanCheck.new :country => "PL", :iban => "_number_"
```

**Comment by g-pavlik** [comment]
True, just read that on wiki. Thanks :)

**Pull request closed without merging**
