### PR TITLE
Aruba specs for command line

### PR DESCRIPTION
**Pull request by thbar**
Hi again,

last bits for today: I added command line specs using Aruba.

To use a recent Aruba I had to update RSpec etc, hope you don't mind.

cheers!

-- Thibaut

### CODE REVIEW

**Comment by LTe** [comment]
We really need cucumber? You can use aruba/api and use rspec :) If you have little free time you can rewrite specs for rspec.
https://github.com/cucumber/aruba/blob/master/lib/aruba/api.rb

Thanks for good piece of code! I love open-source!:)

**Comment by thbar** [comment]
I will rewrite it with RSpec, no worries :)

Envoyé de mon iPhone

Le 3 févr. 2012 à 14:32, "Piotr Niełacny"
reply@reply.github.com
a écrit :

**Comment by thbar** [comment]
Here you are sir :)

**Comment by LTe** [comment]
Great work!;) Thanks a lot for this pull request.

**Pull request merged**
